sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t react_docker -f Dockerfile.dev .

script:
  - docker run -e CI=true react_docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-433879732555"
  bucket_path: "react-docker"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
